### ISSUE TITLE
Header icons 

### ISSUE THREAD

**Issue by lilbaj** [lilbaj/saas-website#2]
@muxlowc
So I have icons on the sides of the title, and I want to keep them beside the title for all screen sizes. For some reason, it really doesn't want to cooperate with me and the icons are going on their own line. It starts doing this when the screen is as 960 and I have no clue why. 

<img width="828" alt="Screen Shot 2020-04-16 at 12 43 21 PM" src="https://user-images.githubusercontent.com/55108804/79483256-0b776f80-7fe0-11ea-80a4-3ae9dfced9c1.png">

`<h1 class="unit xs-1 s-1 m-1 l-1-4 xl-1-4 island-1-2 max-length text-center unit-content-center push-0">
      <i class="icon i-48">
        <img src="images/icon-4.svg" alt="flower icon">
      </i>
      <span class="yotta icon-label">artCHAT</span>
      <i class="icon i-48">
        <img src="images/icon-4.svg" alt="flower icon">
      </i>
    </h1>`

I have tried making the span and the icons inline or inline block- I even tried the flex-row class but they didn't work. Not sure how to fix this.

**Comment by muxlowc** [comment]
@lilbaj  Hmm you might need to make all of your unit sizes equal "-1" (rather than doing l-1-4/xl-1-4) and then add a pad-t and pad-b to your h1 tag.

Hope that helps!

**Comment by lilbaj** [comment]
Yes, it did, it's working perfectly now thank you!
